skip failing test if noiseprotocol unavailable
This test fails in the Debian package (which doesn't currently have
noiseprotocol packaged) and instead of being properly skipped like the
other noise tests, it crashes the test suite:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_magic-wormhole/build/wormhole/test/dilate/test_record.py", line 307, in test_large_frame
    noise0 = build_noise()
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_magic-wormhole/build/wormhole/_dilation/connector.py", line 45, in build_noise
    return NoiseConnection.from_name(NOISEPROTO)
builtins.AttributeError: 'NoneType' object has no attribute 'from_name'

wormhole.test.dilate.test_record.Record.test_large_frame